ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonFootprintTotal";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonFootprintPerformanceClass";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonDeclarationManufacturerDetails";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonDeclarationBatteryModel";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonDeclarationManufacturingLocation";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonFootprintLifecycleBreakdown";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonDeclarationDocReference";
ALTER TABLE "BatteryPassportData" DROP COLUMN "carbonDeclarationWebLink";

ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintTotalValueKgCo2ePerKwh" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintTotalTotalKgCo2e" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintTotalCalculationBasis" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintPerformanceClassValue" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintPerformanceClassStatus" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturerCompanyName" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturerAddress" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturerSustainabilityUrl" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelName" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelChemistry" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelNominalCapacityAh" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelNominalCapacityKwh" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelNominalVoltageV" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationBatteryModelApplication" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturingFacilityName" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturingCity" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationManufacturingCountry" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleRawMaterialExtractionKgCo2e" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleRawMaterialPct" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleManufacturingKgCo2e" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleManufacturingPct" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleDistributionKgCo2e" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleDistributionPct" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleEndOfLifeKgCo2e" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonFootprintLifecycleEndOfLifePct" REAL;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationDocReferenceNumber" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationDocIssuedBy" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationDocIssueDate" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationDocNotifiedBodyReference" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationSustainabilityPageUrl" TEXT;
ALTER TABLE "BatteryPassportData" ADD COLUMN "carbonDeclarationCarbonFootprintReportUrl" TEXT;
